version: '3.8'

services:
  api:
    build: .
    container_name: ultrapdf-backend
    # Volume mapping: Menghubungkan folder lokal dengan folder di dalam Docker
    volumes:
      - .:/app
      # Pastikan folder uploads dan outputs tetap ada
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - PORT=8000
    # Mengaktifkan --reload agar FastAPI otomatis update saat kode berubah
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always